// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserGroupProto.proto

package protobuf.http;

public final class UserGroupProto {
  private UserGroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetTokenCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.GetTokenC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string userPassword = 3;</code>
     */
    java.lang.String getUserPassword();
    /**
     * <code>optional string userPassword = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPasswordBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.GetTokenC}
   */
  public  static final class GetTokenC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.GetTokenC)
      GetTokenCOrBuilder {
    // Use GetTokenC.newBuilder() to construct.
    private GetTokenC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetTokenC() {
      hOpCode_ = "";
      userName_ = "";
      userPassword_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetTokenC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPassword_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.UserGroupProto.GetTokenC.class, protobuf.http.UserGroupProto.GetTokenC.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPassword_;
    /**
     * <code>optional string userPassword = 3;</code>
     */
    public java.lang.String getUserPassword() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPassword_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userPassword = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPasswordBytes() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getUserPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPassword_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getUserPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPassword_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.UserGroupProto.GetTokenC)) {
        return super.equals(obj);
      }
      protobuf.http.UserGroupProto.GetTokenC other = (protobuf.http.UserGroupProto.GetTokenC) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPassword()
          .equals(other.getUserPassword());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USERPASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getUserPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.UserGroupProto.GetTokenC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.GetTokenC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.GetTokenC)
        protobuf.http.UserGroupProto.GetTokenCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.UserGroupProto.GetTokenC.class, protobuf.http.UserGroupProto.GetTokenC.Builder.class);
      }

      // Construct using protobuf.http.UserGroupProto.GetTokenC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        userName_ = "";

        userPassword_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenC_descriptor;
      }

      public protobuf.http.UserGroupProto.GetTokenC getDefaultInstanceForType() {
        return protobuf.http.UserGroupProto.GetTokenC.getDefaultInstance();
      }

      public protobuf.http.UserGroupProto.GetTokenC build() {
        protobuf.http.UserGroupProto.GetTokenC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.UserGroupProto.GetTokenC buildPartial() {
        protobuf.http.UserGroupProto.GetTokenC result = new protobuf.http.UserGroupProto.GetTokenC(this);
        result.hOpCode_ = hOpCode_;
        result.userName_ = userName_;
        result.userPassword_ = userPassword_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.UserGroupProto.GetTokenC) {
          return mergeFrom((protobuf.http.UserGroupProto.GetTokenC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.UserGroupProto.GetTokenC other) {
        if (other == protobuf.http.UserGroupProto.GetTokenC.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPassword().isEmpty()) {
          userPassword_ = other.userPassword_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.UserGroupProto.GetTokenC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.UserGroupProto.GetTokenC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPassword_ = "";
      /**
       * <code>optional string userPassword = 3;</code>
       */
      public java.lang.String getUserPassword() {
        java.lang.Object ref = userPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userPassword = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPasswordBytes() {
        java.lang.Object ref = userPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userPassword = 3;</code>
       */
      public Builder setUserPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPassword = 3;</code>
       */
      public Builder clearUserPassword() {
        
        userPassword_ = getDefaultInstance().getUserPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPassword = 3;</code>
       */
      public Builder setUserPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPassword_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.GetTokenC)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.GetTokenC)
    private static final protobuf.http.UserGroupProto.GetTokenC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.UserGroupProto.GetTokenC();
    }

    public static protobuf.http.UserGroupProto.GetTokenC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetTokenC>
        PARSER = new com.google.protobuf.AbstractParser<GetTokenC>() {
      public GetTokenC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetTokenC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetTokenC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetTokenC> getParserForType() {
      return PARSER;
    }

    public protobuf.http.UserGroupProto.GetTokenC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetTokenSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.GetTokenS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string tokenId = 2;</code>
     */
    java.lang.String getTokenId();
    /**
     * <code>optional string tokenId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenIdBytes();

    /**
     * <code>optional string tokenExpireTime = 3;</code>
     */
    java.lang.String getTokenExpireTime();
    /**
     * <code>optional string tokenExpireTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenExpireTimeBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.GetTokenS}
   */
  public  static final class GetTokenS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.GetTokenS)
      GetTokenSOrBuilder {
    // Use GetTokenS.newBuilder() to construct.
    private GetTokenS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetTokenS() {
      hOpCode_ = "";
      tokenId_ = "";
      tokenExpireTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetTokenS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tokenId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tokenExpireTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.UserGroupProto.GetTokenS.class, protobuf.http.UserGroupProto.GetTokenS.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENID_FIELD_NUMBER = 2;
    private volatile java.lang.Object tokenId_;
    /**
     * <code>optional string tokenId = 2;</code>
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string tokenId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENEXPIRETIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object tokenExpireTime_;
    /**
     * <code>optional string tokenExpireTime = 3;</code>
     */
    public java.lang.String getTokenExpireTime() {
      java.lang.Object ref = tokenExpireTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenExpireTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string tokenExpireTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenExpireTimeBytes() {
      java.lang.Object ref = tokenExpireTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenExpireTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getTokenIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tokenId_);
      }
      if (!getTokenExpireTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tokenExpireTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getTokenIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tokenId_);
      }
      if (!getTokenExpireTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tokenExpireTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.UserGroupProto.GetTokenS)) {
        return super.equals(obj);
      }
      protobuf.http.UserGroupProto.GetTokenS other = (protobuf.http.UserGroupProto.GetTokenS) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getTokenId()
          .equals(other.getTokenId());
      result = result && getTokenExpireTime()
          .equals(other.getTokenExpireTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + TOKENID_FIELD_NUMBER;
      hash = (53 * hash) + getTokenId().hashCode();
      hash = (37 * hash) + TOKENEXPIRETIME_FIELD_NUMBER;
      hash = (53 * hash) + getTokenExpireTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.UserGroupProto.GetTokenS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.UserGroupProto.GetTokenS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.GetTokenS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.GetTokenS)
        protobuf.http.UserGroupProto.GetTokenSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.UserGroupProto.GetTokenS.class, protobuf.http.UserGroupProto.GetTokenS.Builder.class);
      }

      // Construct using protobuf.http.UserGroupProto.GetTokenS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        tokenId_ = "";

        tokenExpireTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.UserGroupProto.internal_static_protobuf_http_GetTokenS_descriptor;
      }

      public protobuf.http.UserGroupProto.GetTokenS getDefaultInstanceForType() {
        return protobuf.http.UserGroupProto.GetTokenS.getDefaultInstance();
      }

      public protobuf.http.UserGroupProto.GetTokenS build() {
        protobuf.http.UserGroupProto.GetTokenS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.UserGroupProto.GetTokenS buildPartial() {
        protobuf.http.UserGroupProto.GetTokenS result = new protobuf.http.UserGroupProto.GetTokenS(this);
        result.hOpCode_ = hOpCode_;
        result.tokenId_ = tokenId_;
        result.tokenExpireTime_ = tokenExpireTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.UserGroupProto.GetTokenS) {
          return mergeFrom((protobuf.http.UserGroupProto.GetTokenS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.UserGroupProto.GetTokenS other) {
        if (other == protobuf.http.UserGroupProto.GetTokenS.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getTokenId().isEmpty()) {
          tokenId_ = other.tokenId_;
          onChanged();
        }
        if (!other.getTokenExpireTime().isEmpty()) {
          tokenExpireTime_ = other.tokenExpireTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.UserGroupProto.GetTokenS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.UserGroupProto.GetTokenS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenId_ = "";
      /**
       * <code>optional string tokenId = 2;</code>
       */
      public java.lang.String getTokenId() {
        java.lang.Object ref = tokenId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tokenId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenIdBytes() {
        java.lang.Object ref = tokenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tokenId = 2;</code>
       */
      public Builder setTokenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tokenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenId = 2;</code>
       */
      public Builder clearTokenId() {
        
        tokenId_ = getDefaultInstance().getTokenId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenId = 2;</code>
       */
      public Builder setTokenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tokenId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenExpireTime_ = "";
      /**
       * <code>optional string tokenExpireTime = 3;</code>
       */
      public java.lang.String getTokenExpireTime() {
        java.lang.Object ref = tokenExpireTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenExpireTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tokenExpireTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenExpireTimeBytes() {
        java.lang.Object ref = tokenExpireTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenExpireTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tokenExpireTime = 3;</code>
       */
      public Builder setTokenExpireTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tokenExpireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenExpireTime = 3;</code>
       */
      public Builder clearTokenExpireTime() {
        
        tokenExpireTime_ = getDefaultInstance().getTokenExpireTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenExpireTime = 3;</code>
       */
      public Builder setTokenExpireTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tokenExpireTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.GetTokenS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.GetTokenS)
    private static final protobuf.http.UserGroupProto.GetTokenS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.UserGroupProto.GetTokenS();
    }

    public static protobuf.http.UserGroupProto.GetTokenS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetTokenS>
        PARSER = new com.google.protobuf.AbstractParser<GetTokenS>() {
      public GetTokenS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetTokenS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetTokenS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetTokenS> getParserForType() {
      return PARSER;
    }

    public protobuf.http.UserGroupProto.GetTokenS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_GetTokenC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_GetTokenC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_GetTokenS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_GetTokenS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024UserGroupProto.proto\022\rprotobuf.http\"D\n" +
      "\tGetTokenC\022\017\n\007hOpCode\030\001 \001(\t\022\020\n\010userName\030" +
      "\002 \001(\t\022\024\n\014userPassword\030\003 \001(\t\"F\n\tGetTokenS" +
      "\022\017\n\007hOpCode\030\001 \001(\t\022\017\n\007tokenId\030\002 \001(\t\022\027\n\017to" +
      "kenExpireTime\030\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_http_GetTokenC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_http_GetTokenC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_GetTokenC_descriptor,
        new java.lang.String[] { "HOpCode", "UserName", "UserPassword", });
    internal_static_protobuf_http_GetTokenS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_http_GetTokenS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_GetTokenS_descriptor,
        new java.lang.String[] { "HOpCode", "TokenId", "TokenExpireTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
