package org.grain.mariadb.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.grain.mariadb.model.base.Testtable;
import org.grain.mariadb.model.base.TesttableCriteria;

public interface TesttableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    long countByExample(TesttableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int deleteByExample(TesttableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int insert(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int insertSelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    List<Testtable> selectByExample(TesttableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    Testtable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Testtable record, @Param("example") TesttableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Testtable record, @Param("example") TesttableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Testtable record);
}